import { Bot, CheckCircle, AlertCircle, Lightbulb, BarChart } from "lucide-react"
import { Progress } from "@/components/ui/progress"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

interface AIAnalysis {
  successProbability: number
  strengths: string[]
  weaknesses: string[]
  recommendations: string[]
}

export function AIReviewSection({ analysis }: { analysis: AIAnalysis }) {
  // Function to determine the color based on probability
  const getProbabilityColor = (probability: number) => {
    if (probability >= 75) return "text-green-500"
    if (probability >= 50) return "text-amber-500"
    return "text-red-500"
  }



  return (
    <Card className="bg-gradient-to-b border-t-2 border-t-purple-500">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-purple-500" />
            <CardTitle className="text-xl">AI-Powered Application Analysis</CardTitle>
          </div>
          <Badge variant="outline" className="bg-purple-500/10 text-purple-400 border-purple-500/30">
            AI-Generated
          </Badge>
        </div>
        <CardDescription>
          This analysis is generated by an AI based on your profile and historical funding data. Results should be used
          as guidance only.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <h3 className="font-medium flex items-center gap-2">
              <BarChart className="h-4 w-4 text-purple-500" />
              Success Probability
            </h3>
            <span className={`font-bold ${getProbabilityColor(analysis.successProbability)}`}>
              {analysis.successProbability}%
            </span>
          </div>
          <div className="relative pt-1">
            <Progress
              value={analysis.successProbability}
              className="h-2"
            />
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <div className="space-y-3">
            <h3 className="font-medium flex items-center gap-2">
              <CheckCircle className="h-4 w-4 text-green-500" />
              Profile Strengths
            </h3>
            <ul className="space-y-2">
              {analysis.strengths.map((strength, index) => (
                <li key={index} className="flex gap-2 text-sm">
                  <span className="text-green-500">+</span>
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="space-y-3">
            <h3 className="font-medium flex items-center gap-2">
              <AlertCircle className="h-4 w-4 text-amber-500" />
              Areas for Improvement
            </h3>
            <ul className="space-y-2">
              {analysis.weaknesses.map((weakness, index) => (
                <li key={index} className="flex gap-2 text-sm">
                  <span className="text-amber-500">-</span>
                  <span>{weakness}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="space-y-3 pt-2">
          <h3 className="font-medium flex items-center gap-2">
            <Lightbulb className="h-4 w-4 text-blue-500" />
            AI Recommendations
          </h3>
          <div className="bg-gradient-to-r from-blue-900/20 to-blue-900/5 p-4 rounded-md">
            <ul className="space-y-2">
              {analysis.recommendations.map((recommendation, index) => (
                <li key={index} className="flex gap-2 text-sm">
                  <span className="text-blue-500">→</span>
                  <span>{recommendation}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
